Allowed for More Modular Account Styling & Improved High Security Pages
Jokes4Miles/emberfire-account pull request #1
Opened 2017-07-26 22:18 UTC by vkoves

High security pages (update email, update password, delete account) now ask for the user's current password instead of using the reauthenticate component. This also fixes an issue caused by `ember-notify`  and makes it so the account menu is more modular so that the config file can have HTML inputted to it.

2017-07-26 23:11 UTC, PrinceCornNM commented
Please resolve issues with the new eslint best practice code styling.

2017-07-27 13:52 UTC, conradlz requested changes
You should take care of those 2 things

2017-07-27 13:52 UTC, PrinceCornNM commented on addon/components/delete-user.js
> +            Ember.Logger.log("ERROR 1");
Remove the logs

2017-07-27 13:52 UTC, PrinceCornNM commented on addon/templates/components/update-password.hbs
> +			{{f.password-field "password" label="Password" }}
Label should probably say new password

2017-07-27 15:23 UTC, vkoves commented
@PrinceCornNM - I've resolved the two issues you had.

2017-07-27 15:24 UTC, PrinceCornNM commented
Thanks merging..

2017-07-27 15:25 UTC, conradlz approved these changes

2017-07-27 15:26 UTC, merged